name: change
version: 0.2.0
description: A Changelog manipulation library. Read/modify/write your CHANGELOG.md. Inspired by keepachangelog.com.
homepage: "https://github.com/f3ath/change"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  markdown: ^4.0.0
  marker: ^0.2.0
  maybe_just_nothing: ^0.4.0
  pub_semver: ^2.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.9.0
  coverage: ^1.0.1
  check_coverage: ^0.0.2
